### ISSUE TITLE
Size is not defined ...Error

### ISSUE THREAD

**Issue by manojjenago** [chranga/renkocharts#4]
Hi,
Thanks for the code to visualize the Renko chart. 
I treid to put together the code and trying to execute, however I am getting error that the Size is not defined 

`    #Format the chart. Give it a title, print the renko box size, last renko close price and actual close price
    plt.title('Renko Chart SPX.lmx size {0}. Last Close:{1}. Adj Close:{2}. Levels: {3}'.format(size, lp, adj_close, step))`

When we are calling the `plot_renko(100, new_df, 20, adj_close)` , but we are not passing the size anywhere to this function...
please let me know if I missed anything here .

**Comment by chranga** [comment]
Size is a global variable. So you need to declare it before you call the plt_renko() function.
The reason for this is because it goes into this function used to output the renko formatted boxes.
`df_to_renko(df, size)`
```
size = 20 #Renko box size
r_bars = df_to_renko(df, size)
print('# of rows in DF:',len(r_bars))
new_df = r_bars[['open','close']]

plot_renko(100, new_df, 20, adj_close)
```

If needed, you can input size as another argument to the plot_renko function, so you can call it using the function instead of via the variable. But this would mean, you will need to update the plot_renko to also include the df_to_renko function aspects too.

Since I had quite a few arguments already, didnt feel to add one more, but you can easily do that. (One can also get confused with the step levels on the x-axis)

Hope this clarifies.

**Comment by manojjenago** [comment]
> Size is a global variable. So you need to declare it before you call the plt_renko() function. The reason for this is because it goes into this function used to output the renko formatted boxes. `df_to_renko(df, size)`
> 
> ```
> size = 20 #Renko box size
> r_bars = df_to_renko(df, size)
> print('# of rows in DF:',len(r_bars))
> new_df = r_bars[['open','close']]
> 
> plot_renko(100, new_df, 20, adj_close)
> ```
> 
> If needed, you can input size as another argument to the plot_renko function, so you can call it using the function instead of via the variable. But this would mean, you will need to update the plot_renko to also include the df_to_renko function aspects too.
> 
> Since I had quite a few arguments already, didnt feel to add one more, but you can easily do that. (One can also get confused with the step levels on the x-axis)
> 
> Hope this clarifies.

Thanks, this makes sense. I will do the changes as required.
Thanks,
Manoj
